#!/usr/bin/env bash
#Script displaying numbers 1..100, displaying buzzwords on multiples of 3 & 5

num=1
num_target=100

while [ $num -le $num_target ]; do
    if  (( num % 3 == 0 ))  && (( num % 5 == 0 )) ; then
	echo "FizzBuzz"
    elif  (( num % 3 == 0 )) ; then
	echo "Fizz"
    elif (( num % 5 == 0 )) ; then
	echo "Buzz"
    else
	echo $num
    fi
    ((num=num+1))
done

	

