#!/usr/bin/env bash
#Script listing Best School 10 times, but saying Hi the 9th iteration
i=1
target=10

while [ $i -le $target ];
do
	echo "Best School"
	((i++))

	if [ $i -eq 9 ];
	then
    echo "Best School"
    echo "Hi"
    ((i++))
fi
    done
