#!/usr/bin/env bash
#While loop with 20 number iterations, displaying special text on iteration 4, 9, and 17

i=1
target=20

while [ $i -le $target ];
do
    echo $i
    ((i++))
    if [[ $i -eq 4 || $i -eq 9 || $i -eq 17 ]];
    then
	:
	fi

    case $i in
	4)
	    echo $i
	    echo "bad luck from China"
	    ((i++))
	    ;;
	9)
	    echo $i
	    echo "bad luck from Japan"
	    ((i++))
	    ;;
	17)
	    echo $i
	    echo "bad luck from Italy"
	    ((i++))
	    ;;
    esac
    done
