#!/usr/bin/env bash
#For loop listing current directory contents in long form, only showing part of file name

for file in *;
do
	    ls -l
	    if [[ "$file" == ?-* ]];
	    then
	       filename="${file#*-}"
	       echo "$filename"
	    else
            then
		   echo "$file"
	    fi
done
