#!/usr/bin/env bash
#For loop listing current directory contents, only showing part of file name

for file in *;
do
    
	    if [[ $file == *-* ]];
	    then
		echo "${file#?-*}"
	    else
		echo $file
	    fi
	    
done
